---
- name: Ensure servers are provisioned in vpc
  hosts: localhost
  gather_facts: false
  vars:
    # requires ec2_stack_name, ec2_region and ec2_key_name
    # ec2_exact_count: 1
    # ec2_vpcidr: 10.251.0.0/16
    # ec2_subnetcidr: 10.251.1.0/24
    # ec2_az: a

  tasks:
  - name: create a cloudformation stack
    cloudformation:
      stack_name: "ansible-cloudformation"
      state: "present"
      region: "us-west-1"
      disable_rollback: true
      template: "aws.template"
      template_parameters:
        KeyName: "hellowebui_key"
        AMI: "ami-070a1367"
        # DiskType: "ephemeral"
        # InstanceType: "m1.small"
        # ClusterSize: 3
      tags:
        Stack: "ansible-cloudformation"

  # - name: Display stack instances info
  #   debug:
  #     var: ec2
  #     verbosity: 1

  # - name: Ensure all instances are ready
  #   wait_for:
  #     port: 22
  #     host: "{{ item.public_ip }}"
  #     search_regex: OpenSSH
  #   with_items: "{{ ec2.tagged_instances }}"

  # - name: Pause to let cloud init to complete
  #   pause:
  #     seconds: 90

  # - name: Build group of instances
  #   add_host:
  #     name: "{{ item.public_dns_name }}"
  #     groups: web
  #     ansible_user: centos
  #     ansible_host: "{{ item.public_ip }}"
  #     ansible_ssh_private_key_file: "{{ ec2_private_key_file | default(omit) }}"
  #   with_items: "{{ ec2.tagged_instances }}"

