---
- name: install firefox and dependencies
  yum:
    name:
      - firefox
      - Xvfb
      - libXfont
      - Xorg
    state: present

- name: install the 'X Window System' package group
  yum:
    name: "@X Window System"
    state: present

- name: install the 'GNOME Desktop' package group
  yum:
    name: "@^gnome-desktop-environment"
    state: present

- name: install the 'Fonts' package group
  yum:
    name: "@Fonts"
    state: present

- name: Launch an XWindows Virtual Frame Buffer(XVFB) session on display port 99
  shell: Xvfb :99 -ac -screen 0 1280x1024x24 &
  args:
    executable: /bin/bash

- name: Extract geckodriver-v0.24.0-linux64.tar.gz into /usr/local/bin
  unarchive:
    src: https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Start a standalone server
  selenium:
    role: standalone
    state: running
  environment:
    DISPLAY: :99