---
- name: Ensure servers are deprovisioned in vpc
  hosts: localhost
  gather_facts: false
  tags:
    - deprovision

  tasks:
  - name: delete a stack
    cloudformation:
      stack_name: "{{ cli_stackname }}"
      state: "absent"
      region: "{{ cli_ec2region }}"