---
- name: Ensure servers are deprovisioned in vpc
  hosts: localhost
  gather_facts: false
  tags:
    - deprovision

  tasks:
  - name: Find last application images
    ec2_ami_facts:
      owners: self
      region: "{{ cli_ec2region }}"
      filters:
        "tag:Name": "{{ g_aminame }}"
        "tag:Build": "{{ g_aminame }}-{{ cli_ci_pipeline_id }}"
        "tag:OpCo": "{{ g_opco }}"
    register: ami_find

  - name: delete a deploy
    terraform:
      project_path: '{{ cli_tf }}'
      state: absent
      force_init: true
      backend_config:
        key: "{{ cli_stackname }}"
      variables:
        AMI: "{{ ami_find.images[0].image_id }}"
        stackname: "{{ cli_stackname }}"
        environment: "{{ cli_deploymentenv }}"
        aws_access_key: "{{ cli_aws_access_key }}"
        aws_secret_key: "{{ cli_aws_secret_key }}"
    register: stack