---
- name: Validate that stack is conformant
  hosts: localhost
  gather_facts: false
  tags:
    - provision-conformity

  tasks:
  - name: Find last application images
    ec2_ami_facts:
      owners: self
      region: "{{ cli_ec2region }}"
      filters:
        "tag:Name": "{{ g_aminame }}"
        "tag:Build": "{{ g_aminame }}-{{ cli_ci_pipeline_id }}"
        "tag:OpCo": "{{ g_opco }}"
    register: ami_find

  - name: Terraform init
    command: terraform init -backend-config="key=staging"
    args:
      chdir: $PWD/terraform
    when: "ami_find"

  - name: Terraform plan
    command: >-
      terraform plan
      -var 'AMI={{ ami_find.images[0].image_id }}'
      -var 'stackname={{ cli_stackname }}'
      -var 'environment={{ cli_deploymentenv }}'
      -var 'aws_access_key={{ cli_aws_access_key }}'
      -var 'aws_secret_key={{ cli_aws_secret_key }}'
      -out ./plan.tfstate
    args:
      chdir: $PWD/terraform
    when: "ami_find"
    # register: result

  # - name: Show terraform stdout
  #   debug: msg="{{ result.stdout_lines }}"